<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>
<div class="layered-filter-block-items">
<?php if ($block->canShowBlock()) : ?>
    <div class="block filter" id="layered-filter-block" data-mage-init='
    {
        "collapsible":
        {
            "openedState": "active",
            "collapsible": true,
            "active": false,
            "collateral":
            {
                "openedState": "filter-active",
                "element": "body"
            }
        }
    }'>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?= /* @noEscape */ $filtered ?>">
            <strong data-role="title"><?= $block->escapeHtml(__('Shop By')); ?></strong>
        </div>
        <div class="block-content filter-content filter-content-one ">
            
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter) : ?>
                <?php if ($filter->getItemsCount()) : ?>
                    <?php if (!$wrapOptions) : ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= $block->escapeHtml(__('Shopping Options')) ?></strong>
                        <div class="filter-options not-fixed" id="narrow-by-list" data-role="content" data-mage-init='
                        {
                            "accordion":
                            {
                                "openedState": "active",
                                "collapsible": true,
                                "active": false,
                                "multipleCollapsible": false
                            }
                        }'>
                        <?php $wrapOptions = true;
                        endif; ?>
                    <div data-role="collapsible" class="filter-options-item">
                        <div data-role="title" class="filter-options-title"><?= $block->escapeHtml(__($filter->getName())) ?></div>
                        <div data-role="content" class="filter-options-content"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></div>
                    </div>
                <?php endif; ?>
                
            <?php endforeach; ?>

            <?php if ($wrapOptions) : ?>
              <div style="display: block;" data-role="collapsible" class="filter-options-item more-items">
                        <div data-role="title" class="filter-options-title"><a href="javascript:;" class="morefilter">Meer filters</a></div>
                       
                    </div>
                </div>
            <?php else : ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
            <?php endif; ?>
        </div>
        <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear">
                        <span><?= $block->escapeHtml(__('Clear All')) ?></span>
                    </a>
                </div>
            <?php endif; ?>
    </div>
<?php endif; ?>
<div class="filter-right">
  <div class="filter-sort">


   </div> 

</div>  
</div>
<script>
      require([
          'jquery'
      ], function ($) {
         $sort_data =  $('.toolbar-sorter.sorter').html();
         $('.filter-right .filter-sort').html($sort_data);
         $tool_html = $('.filter-content-one + .filter-current').html();
         $clear = $('.block-actions.filter-actions').html();
        // if($('.toolbar.toolbar-products').find('.filter-current').length)
        if($('.filter-content-one + .filter-current').length) {
           $('.toolbar.toolbar-products').append('<div class="item-show-filter"><div class="filter-current">'+$tool_html+'</div>'+$clear+'</div>');
           $('.item-show-filter .filter-current strong.block-subtitle').text('Gekozen filters:');
           $('.item-show-filter').find('a.action.clear.filter-clear').text('Filters wissen');
         }
         $('.filter-options-item.more-items').click(function(e){
              e.stopPropagation(); 
              $('.fixed-filter-desktop').fadeToggle();
              $('.sidebar.sidebar-main').toggleClass('overlay'); 
         })
        
         if($('.toolbar.toolbar-products').find('.pages').length) {
            $htmls = $('.toolbar.toolbar-products').find('.pages').html();
            $('.main-block.popular-block').append('<div class="pagination">'+$htmls+'</div>');
            $current = $('.pagination ul.items.pages-items').find('.item.current').find('strong.page').find('span.label + span').text();

            $last = $('.pagination ul.items.pages-items').find('li.pages-item-next').prev('.item').find('a').find('span.label + span').text();

            $fuultext = '<span>Pagina '+$current+' Van '+$last+'</span>';
            $('.pagination ul.items.pages-items').find('.item.current').html($fuultext);
         }

         $('.fixed-filter-desktop, .layered-filter-block-items').on('click', function(e){ 
               e.stopPropagation(); 
         })

         $('.close-filter, .sidebar.sidebar-main').on('click', function(){
            $('.sidebar.sidebar-main').removeClass('overlay');
            $('.fixed-filter-desktop').fadeOut();

         });

         
      });
  </script>
  <div class="fixed-filter-desktop">
     <div class="filter-block-top">
        <h3>Filters</h3>
        <a class="close-filter" href="javascript:;"></a>
     </div>
    <div class="filter-block-bottom">
    <?php if ($block->canShowBlock()) : ?>
    <div class="block filter" id="layered-filter-block" data-mage-init='
    {
        "collapsible":
        {
            "openedState": "active",
            "collapsible": true,
            "active": false,
            "collateral":
            {
                "openedState": "filter-active",
                "element": "body"
            }
        }
    }'>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?= /* @noEscape */ $filtered ?>">
            <strong data-role="title"><?= $block->escapeHtml(__('Shop By')); ?></strong>
        </div>
        <div class="block-content filter-content">
            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear">
                        <span><?= $block->escapeHtml(__('Clear All')) ?></span>
                    </a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter) : ?>
                <?php if ($filter->getItemsCount()) : ?>
                    <?php if (!$wrapOptions) : ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= $block->escapeHtml(__('Shopping Options')) ?></strong>
                        <div class="filter-options fixed-filter" id="narrow-by-list" data-role="content" data-mage-init='
                        {
                            "accordion":
                            {
                                "openedState": "active",
                                "collapsible": true,
                                "active": false,
                                "multipleCollapsible": false
                            }
                        }'>
                        <?php $wrapOptions = true;
                        endif; ?>
                    <div data-role="collapsible" class="filter-options-item">
                        <div data-role="title" class="filter-options-title"><?= $block->escapeHtml(__($filter->getName())) ?></div>
                        <div data-role="content" class="filter-options-content"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></div>
                    </div>
                <?php endif; ?>
                
            <?php endforeach; ?>

            <?php if ($wrapOptions) : ?>
              
            <?php else : ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>


  </div>  
    </div>
 </div>   
<script>
    require([
        'jquery'
    ], function ($) {
        if($('.block-actions.filter-actions').length) {
          $clear = $('.block-actions.filter-actions a').attr('href');
          $('.filter-block-bottom').after('<div class="bottom-btns"><div class="btns-item"><a class="btn-item" href='+$clear+'>Wissen</a></div></div>');
      }
    });
</script>