<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();

if (!$_product instanceof \Magento\Catalog\Model\Product) {
    return;
}

$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>
<div class="accordion-panel">
<?php if ($_attributeValue): 
		
?>
<div class="accordion-row">
	<div class="product attribute <?= /* @escapeNotVerified */ $_className ?>">
		<div class="accordion-title strng-title"><?php echo __('Beschrijving') ?></div>
	    <?php if ($renderLabel): ?><strong class="type"><?= /* @escapeNotVerified */ $_attributeLabel ?></strong><?php endif; ?>
	    <div class="usp-block usp-blockvalue value accordion-content" <?= /* @escapeNotVerified */ $_attributeAddAttribute ?>><div><?= /* @escapeNotVerified */ $_attributeValue ?></div></div>
	</div>
</div>
<?php if($_className=='overview'){ 
$myattribute = $_product->getResource()->getAttribute('format_product')->getFrontend()->getValue($_product);

if($myattribute){
	?>
<div class="accordion-row">	
		<div class="accordion-title strng-title"><?php echo __('Formaat product') ?></div>
		<div class="accordion-content">

			<div>	
				<?php echo $myattribute; ?>
				
			</div>
		</div>
</div>
<?php } } ?>	
<?php endif; ?>
</div>




