
<ul class="list-style">
	<li><i class="fas fa-check"></i>30 dagen retourgarantie</li>
    <li><i class="fas fa-check"></i>Gratis ophalen in Sint-Oedenrode</li>
	<li><i class="fas fa-check"></i>Gratis verzending vanaf €&nbsp;500,00 binnen de Benelux</li>
	<li><i class="fas fa-check"></i>Wij scoren een 9.2 door 55 beoordelingen</li>
</ul>
<div class="payment-link" style="margin-bottom: -14px;">
	<ul style="width: 100%; margin-left: 0%;">
		<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/Giropay.svg');  ?>"></a></li>
		<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/master.png');  ?>"></a></li>
		<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/visa.svg');  ?>"></a></li>
		<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/iDeal.svg');  ?>"></a></li>
		<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/Mistercash.svg');  ?>"></a></li>
		<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/MyBank.svg');  ?>"></a></li>
	</ul>
	<ul style="width: 100%; margin-left: 0%;">
		
		<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/Overboeking.svg');  ?>"></a></li>
		<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/Paypal.svg');  ?>"></a></li>
		<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/Przelewy24.svg');  ?>"></a></li>
		<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/Sofort.svg');  ?>"></a></li>
	</ul>
</div>