<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>

        <form class="form subscribe"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <input name="email" type="email" id="newsletter" class="emailadd"
                               placeholder="<?= $block->escapeHtml(__('Enter your email address')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"
                        />
                                <span>
                                <input type="checkbox" title="<?php echo __('Sign Up for Newsletter') ?>" name="dummy" value="" id="is_subscribed_footer"  style="width: auto;" data-validate="{required:true}"/>
                                <label for="is_subscribed_footer" class="checkbtn">Ik ga akkoord met de voorwaarden    
                                </label>
                                </span>
                                <div class="actions">
                                <button
                                        title="<?= $block->escapeHtmlAttr(__('Aanmelden')) ?>"
                                        type="submit"
                                        aria-label="Subscribe">
                                    <span><?= $block->escapeHtml(__('Aanmelden')) ?></span>
                                </button>
                            </div>
        </form>
    
