<!-- begin content -->
		<section id="content-wrap" >
			<!-- begin mega-categories-wrap-->
			<section class="mega-categories-wrap">
				<div class="container">
					<div class="row">
						<div class="sidebar-block">
							<div class="s-panel">
								<h4>Categorie</h4>
								<ul>
									<li><a href="#">Luifels<em>(7) </em></a></li>
									<li><a href="#">Canopies <em>(19)</em></a></li>
									<li><a href="#">Kriks <em>(1)</em></a></li>
									<li><a href="#">Bescherming <em>(5)</em></a></li>
									<li><a href="#">Roofracks <em>(45)</em></a></li>
									<li><a href="#">Dakdragers <em>(2)</em></a></li>
									<li><a href="#">Daktenten <em>(9)</em></a></li>
									<li><a href="#">Camper units<em> (2)</em></a></li>
									<li><a href="#">Roofconversions <em>(2)</em></a></li>
									<li><a href="#">Bumpers <em>(12)</em></a></li>
								</ul>
								<a href="#" class="show-more"><i class="fas fa-plus"></i>Toon meer</a>
							</div>
							<div class="s-panel">
								<h4>Merk</h4>
								<ul>
									<li><a href="#">Alu-Cab <em>(15) </em></a></li>
									<li><a href="#">ARB<em>(1)</em></a></li>
									<li><a href="#">Big Country <em>(79)</em></a></li>
									<li><a href="#">Clearview<em>(8)</em></a></li>
									<li><a href="#">E-Z Up<em>(6)</em></a></li>
									<li><a href="#">EZDown<em>(10)</em></a></li>
									<li><a href="#">Gobi-X<em>(22)</em></a></li>
									<li><a href="#">HEBE<em> (3)</em></a></li>
									<li><a href="#">James Baroud<em>(7)</em></a></li>
									<li><a href="#">Lazer <em>(31)</em></a></li>
								</ul>
								<a href="#" class="show-more"><i class="fas fa-plus"></i>Toon meer</a>
							</div>
						</div>
						<div class="categories-block">
							<div class="intro-panel">
								<h3>Exterieur</h3>
								<p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Nullam quis risus eget urna mollis ornare vel eu leo. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
								<a href="#" class="read-more">Lees meer<i class="fas fa-angle-down"></i></a>
							</div>
							
							<div class="row">
								<div class="col1">
									<a href="http://devserver3.nl/exterieur/dak/daktenten.html"><div class="categories-panel">
										<figure><img src="<?php echo $block->getViewFileUrl('images/cat-img1.png');?>"></figure>
										<h4>Daktenten</h4>
									</div></a>
								</div>
								<div class="col1">
									<a href="http://devserver3.nl/exterieur/bumpers.html"><div class="categories-panel">
										<figure><img src="<?php echo $block->getViewFileUrl('images/cat-img2.png');?>"></figure>
										<h4>Bumpers</h4>
									</div></a>
								</div>
								<div class="col1">
									<a href="http://devserver3.nl/exterieur/verlichting/lieren.html"><div class="categories-panel">
										<figure><img src="<?php echo $block->getViewFileUrl('images/cat-img3.png');?>"></figure>
										<h4>Lieren</h4>
									</div></a>
								</div>
								<div class="col1">
									<a href="http://devserver3.nl/exterieur/verlichting.html"><div class="categories-panel">
										<figure><img src="<?php echo $block->getViewFileUrl('images/cat-img4.png');?>"></figure>
										<h4>Verlichting</h4>
									</div></a>
								</div>
								<div class="col1">
									<a href="http://devserver3.nl/exterieur/koelkasten.html"><div class="categories-panel">
										<figure><img src="<?php echo $block->getViewFileUrl('images/cat-img5.png');?>"></figure>
										<h4>Koelkasten</h4>
									</div></a>
								</div>
								<div class="col1">
									<a href="http://devserver3.nl/exterieur/dagdragers.html"><div class="categories-panel">
										<figure><img src="<?php echo $block->getViewFileUrl('images/cat-img6.png');?>"></figure>
										<h4>Dagdragers</h4>
									</div></a>
								</div>
								<div class="col1">
									<a href="http://devserver3.nl/exterieur/stoelhoezen.html"><div class="categories-panel">
										<figure><img src="<?php echo $block->getViewFileUrl('images/cat-img7.png');?>"></figure>
										<h4>Stoelhoezen</h4>
									</div></a>
								</div>
								<div class="col1">
									<a href="http://devserver3.nl/exterieur/verlichting/verbrede-spiegels.html"><div class="categories-panel">
										<figure><img src="<?php echo $block->getViewFileUrl('images/cat-img8.png');?>"></figure>
										<h4>Verbrede spiegels</h4>
									</div></a>
								</div>
							</div>
							
							<div class="seo-block">
								<h3>De beste exterieur producten voor uw offroad voertuig</h3>
								<p>Hier vindt u de beste onderdelen en uitrustingen voor 4x4 auto's! Voor welk doel u de auto ook gebruikt. Als werkpaard, of om hulp te bieden in moeilijk begaanbare gebieden zoals de tropen, of als avontuurlijk vervoers- of verblijfsmiddel, het maakt niet uit. In deze webshop vindt u steeds meer van uw gading, want dagelijks breiden we het productaanbod uit.</p>
								<p>Omdat u in alle situaties maximaal op uw auto en uw uitrusting moet kunnen vertrouwen, zeker in crusiale situaties, bieden wij alleen producten aan van de hoogste kwaliteit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Nullam quis risus eget urna mollis ornare vel eu leo. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Nulla vitae elit libero, a pharetra augue.</p>
							</div>
							
						</div>
					</div>
				</div>
			</section>			
			<!-- finish mega-categories-wrap -->
		</section>
		<!-- finish content -->

	