</section>
    <!-- end content -->
    
<!-- start footer -->
    <footer id="footer-wrap">

            <!-- start copy block -->
            <div class="footerlinks-block">
                <div class="container">
          <div class="row">
            <?php echo $this->getLayout()
      ->createBlock('Magento\Cms\Block\Block')
      ->setBlockId('footer_social_block')
      ->toHtml(); ?>
         <?php echo $this->getLayout()
      ->createBlock('Magento\Cms\Block\Block')
      ->setBlockId('footer_menu_block')
      ->toHtml(); ?>
          </div>
        </div>
            </div>
            <!-- end copy block -->
      
       <!-- start copy block -->
            <div class="copyright-block">
                <div class="container">
          <div class="row space-between">
             <?php echo $this->getLayout()
      ->createBlock('Magento\Cms\Block\Block')
      ->setBlockId('footer_copyright_menu')
      ->toHtml(); ?>
          </div>
        </div>
            </div>
            <!-- end copy block -->

    </footer>
    <!-- end footer -->
    <script>
    require([
        'jquery',         
    ], function($){
        $('.accordion-panel .accordion-row').each(function(index ){
          
          if(index == 0) {
            $(this).addClass('active');
          } 
        });
        $('.accordion-panel .accordion-row .accordion-title').on('click', function(){
          
          $(this).siblings('.accordion-content').slideToggle();
          $(this).parents('.accordion-row').toggleClass('active');

          return false;
        })
        
    });
</script>