</section>
    <!-- end content -->
    
<!-- start footer -->
    <footer id="footer-wrap">

            <!-- start copy block -->
            <div class="footerlinks-block">
                <div class="container">
          <div class="row">
            <div class="col-3">
              <a href="#" class="footerlogo"><img src="images/logo.png" alt=""/></a>
              <ul class="social-links">
                <li><a href="#"><i class="social-icon insta-icon"></i></a></li>
                <li><a href="#"><i class="social-icon facebook-icon"></i></a></li>
              </ul>
            </div>
            <div class="col-3">
              <h4>Klantenservice</h4>
              <ul class="ulinks">
                <li><a href="#">Onze garanties</a></li>
                <li><a href="#">Retourbeleid</a></li>
                <li><a href="#">Bezorgkosten</a></li>
                <li><a href="#">Levertijden</a></li>
                <li><a href="#">Betalen</a></li>
                <li><a href="#">Kleuren</a></li>
              </ul>
            </div>
            <div class="col-3">
              <h4>Showroom</h4>
              <address>
                Arkansasdreef 34d <br>
                3565 AS Utrecht
              </address>
              <table>
                <tr><td>Ma - Do</td><td>Gesloten</td></tr>
                <tr><td>Ma - Do</td><td>10:00 - 17:00</td></tr>
              </table>
            </div>
            <div class="col-3">
              <h4>Contact</h4>
              <address>
                Masterbed BV<br>
                Batenburgweg 7<br>
                3769 CB  Soesterberg-Noord<br><br>

                <a href="#">(0343) 414 128</a><br>
                <a href="#">info@misterbed.nl</a><br><br>

                BTW NL8131.12.278B01<br>
                KvK 30.19.46.00
              </address>
            </div>
          </div>
        </div>
            </div>
            <!-- end copy block -->
      
       <!-- start copy block -->
            <div class="copyright-block">
                <div class="container">
          <div class="row space-between">
            <div class="column-left">
              <ul class="paymentlist">
                <li><img src="images/visa.png" alt=""/></li>
                <li><img src="images/mastercard.png" alt=""/></li>
                <li><img src="images/ideal.png" alt=""/></li>
                <li><img src="images/paypal.png" alt=""/></li>
              </ul>
            </div>
            <div class="column-right">
              <ul class="copyrightlist">
                <li><span>© 2020 Misterbed</span></li>
                <li><a href="#">Privacy beleid</a></li>
                <li><a href="#">Gebruikersvoorwaarden</a></li>
                <li><a href="#">Cookies</a></li>
                <li><a href="#">Klantenreacties</a></li>
              </ul>
            </div>
          </div>
        </div>
            </div>
            <!-- end copy block -->

    </footer>
    <!-- end footer -->