		<!-- main-block -->
		<section id="banner-wrap">
			<div class="container">
				<div class="inner">
					<div class="row">
						<?php
							echo $this->getLayout()
							->createBlock('Magento\Cms\Block\Block')
							->setBlockId('home_banner')
							->toHtml();
						?>
						<a href="#" class="downbtn"></a>
					</div>
				</div>
			</div>
		</section>
		<!-- main-block -->
		<aside class="main-block outlet-block">
				<div class="container">
					<div class="row row-less10">
						<div class="col-3">
							<div class="outlet-panel" style="background: url(./images/img1.png)no-repeat center/cover;">
								<a href="#" class="primarybtn">Peuterbed</a>
							</div>
						</div>
						<div class="col-3">
							<div class="outlet-panel" style="background: url(./images/img2.png)no-repeat center/cover;">
								<a href="#" class="primarybtn">Stapelbed</a>
							</div>
						</div>
						<div class="col-3">
							<div class="outlet-panel" style="background: url(./images/img3.png)no-repeat center/cover;">
								<a href="#" class="primarybtn">Tienerkamer</a>
							</div>
						</div>
						<div class="col-3">
							<div class="outletblank-panel">
								<a href="#" class="btn">Outlet <i></i></a>
							</div>
						</div>
					</div>
				</div>
			</aside>

			<aside class="main-block popular-block">
				<div class="container">
					<div class="row row-less20">
						<div class="col-12">
							<h3>Populair bij Misterbed</h3>
						</div>
						<div class="col-3">
							<div class="popular-panel">
								<figure>
									<img src="images/mask-0.png" alt="">
									<figcaption>Meest Verkocht</figcaption>
									<i class="fav-icon"></i>
								</figure>
								<div class="popular-text">
									<h4>Carina Ledikant</h4>
									<div class="d-flex">
										<span class="pricetag oldpricetag">Elders <sub>€ 500,-</sub></span>
										<span class="pricetag">Vanaf <sub>€ 300,-</sub></span>
									</div>
									<span class="check-list">Uit voorraad leverbaar</span> 
								</div>
							</div>
						</div>
						<div class="col-3">
							<div class="popular-panel">
								<figure>
									<img src="images/mask-1.png" alt="">
									<i class="fav-icon full-heart-icon"></i>
								</figure>
								<div class="popular-text">
									<h4>Carina Ledikant</h4>
									<div class="d-flex">
										<span class="pricetag oldpricetag">Elders <sub>€ 400,-</sub></span>
										<span class="pricetag">Nu <sub>€ 200,-</sub></span>
									</div>
									<span class="list">Binnen 4 weken in huis</span> 
								</div>
							</div>
						</div>
						<div class="col-3">
							<div class="popular-panel">
								<figure>
									<img src="images/mask-2.png" alt="">
									<i class="fav-icon"></i>
								</figure>
								<div class="popular-text">
									<h4>Carina Ledikant</h4>
									<div class="d-flex">
										<span class="pricetag oldpricetag"></span>
										<span class="pricetag">Vanaf <sub>€ 500,-</sub></span>
									</div>
									<span class="check-list">Uit voorraad leverbaar</span> 
								</div>
							</div>
						</div>
						<div class="col-3">
							<div class="popular-panel">
								<figure>
									<img src="images/mask-3.png" alt="">
									<i class="fav-icon"></i>
								</figure>
								<div class="popular-text">
									<h4>Carina Ledikant</h4>
									<div class="d-flex">
										<span class="pricetag oldpricetag">Elders <sub>€ 700,-</sub></span>
										<span class="pricetag">Vanaf <sub>€ 600,-</sub></span>
									</div>
									<span class="list">Binnen 4 weken in huis</span> 
								</div>
							</div>
						</div>
					</div>
				</div>
			</aside>

			<aside class="main-block view-block">
				<div class="container">
					<div class="inner">
						<div class="row">
							<div class="column-left">
								<div class="left-caption">
									<h2>Alles voor een ontspannen zondagochtend</h2>
									<a href="#" class="btn">Bekijk <i></i></a>
								</div>
							</div>	
							<div class="column-right">
								<figure style="background: url(./images/m-img-1.png)no-repeat center/cover;">
									<span class="viewpricetag">Dekbed Bee Bee <em>€38,-</em></span>
								</figure>
							</div>
						</div>
					</div>
				</div>
			</aside>

			<aside class="main-block services-block">
				<div class="container">
					<ul class="row">
						<li class="col-4">
							<div class="services-panel">
								<i class="icons truck-icon"></i>
								<strong>Gratis thuisbezorgd</strong>
							</div>
						</li>
						<li class="col-4">
							<div class="services-panel">
								<i class="icons security-icon"></i>
								<strong>Ruim 15 jaar online</strong>
							</div>
						</li>
						<li class="col-4">
							<div class="services-panel">
								<i class="icons eurohand-icon"></i>
								<strong>Altijd de beste prijs</strong>
							</div>
						</li>
					</ul>
				</div>
			</aside>
		