		<!-- main-block -->
		<section id="banner-wrap">
			<div class="container">
				<div class="inner">
					<div class="row">
						<?php
							echo $this->getLayout()
							->createBlock('Magento\Cms\Block\Block')
							->setBlockId('home_banner')
							->toHtml();
						?>
						<a href="#" class="downbtn"></a>
					</div>
				</div>
			</div>
		</section>
		<!-- main-block -->
		<?php //echo $block->getLayout()->createBlock('Rokanthemes\Blog\Block\Sidebar\Recent')->setTemplate('Rokanthemes_Blog::sidebar/cathome.phtml')->toHtml();?>
		<!-- main-block -->
			<aside class="main-block outlet-block">
				<div class="container">
					<div class="row row-less10">
						<?php
							echo $this->getLayout()
							->createBlock('Magento\Cms\Block\Block')
							->setBlockId('home_custom_repeater')
							->toHtml();
						?>
					</div>
				</div>
			</aside>
			<!-- main-block -->			 
			<aside class="main-block popular-block">
				<div class="container">
					<?php
					$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
					$helperImport = $objectManager->get('\Magento\Catalog\Helper\Image');
					$whish = $objectManager->get('\Magento\Wishlist\Helper\Data');

					$productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
					$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
					$listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
					$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
					$collection = $productCollection->create()
					            ->addAttributeToSelect('*')
					             ->addAttributeToFilter('featured_product', '1')
					             ->addAttributeToSort('price', 'DESC')
					            ->load();
					 $productcount=$collection->count();
					 $wishlist = $objectManager->get('\Magento\Wishlist\Model\Wishlist');

					 if($productcount==0)
					 {
					 	
					 }
					 else
					 {
					 ?>
					<div class="row row-less20">
						<div class="col-12">
							<h3><?php echo __('Populair bij Misterbed') ?></h3>
						</div>
						<?php 
						foreach ($collection as $product)
						{
					     $pname=$product->getName();
					     $productprice=$product->getPrice();
					     $producturl=$product->getProductUrl();
					     $psdescription=$product->getShortDescription();
					     $formattedPrice = $priceHelper->currency($productprice, true, false);
					   // $imageUrl = $this->getUrl().'pub/media/catalog/product'.$product->getImage();
					    $imageUrl = $helperImport->init($product, 'product_page_image_large')->setImageFile($product->getFile())->resize(298,256)->getUrl();
					     $addToCartUrl =  $listBlock->getAddToCartUrl($product);
					     $orgprice = $priceHelper->currency($product->getPrice() , true, false);
						 $specialprice = $priceHelper->currency($product->getSpecialPrice(), true, false);	
						 $is_most = $product->getAttributeText('most_popular_procuct'); 
						 $is_most_text = $product->getData('most_popular_ribbon_text');
						  $_getMyAttr = $product->getResource()->getAttribute('most_popular_ribbon_text');
						  $attrTestValue = $_getMyAttr->getFrontend()->getValue($product);
						  /* echo "<pre>";
                       var_dump($_getMyAttr->debug());
                       echo "</pre>"; */
						 //$wishlistHelper->getWishlistItemCollection()->addFieldToFilter('product_id', $product->getId());	
						// $postDataHelper = $objectManager->helper('Magento\Framework\Data\Helper\PostHelper');
                        //echo $postData = $postDataHelper->getPostData($block->getAddToCartUrl($product), ['product' => $product->getEntityId()])			 
					     /*echo "<pre>";
					     var_dump($product->debug());
					     echo "<pre>"; */ 
						?>
						<?php //echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($product); ?>
						
						<?php /*
							echo "<pre>";
							var_dump($wishlist->getAddParams($product)->debug());
							echo "<pre>"; */
						 ?>
						<div class="col-3">
							<div class="popular-panel">
								<figure onclick="location.href=<?php echo $producturl ;?>" style="background: rgba(0,0,0,0.5); cursor: pointer;">
									<img src="<?php echo $imageUrl; ?>" alt="">
									<?php if($is_most == 'Yes' && $is_most_text) { ?>
										<figcaption><?php echo $is_most_text; ?></figcaption>
									<?php } ?>									
									<a href="#" data-post='<?php echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($product); ?>' class="action towishlist" data-action="add-to-wishlist"><i class="fav-icon"></i></a>
								</figure>
								<div class="popular-text">
									<h4 onclick="location.href=<?php echo $producturl ;?>" style="cursor: pointer;"><?php echo $pname; ?></h4>
									 <?php if($product->getSpecialPrice() > 0) { ?>
                                    <div class="d-flex">
                                        <span class="pricetag oldpricetag">Elders  <sub><?php echo $orgprice; ?>,-</sub></span>
                                        <?php if($specialprice) { ?>
                                        <span class="pricetag">Vanaf <sub><?php echo $specialprice; ?>,-</sub></span>
                                        <?php } ?>
                                    </div>
                                   <?php } else { ?>
                                    <div class="d-flex">                                       
                                        
                                        <span class="pricetag">Vanaf <sub><?php echo $orgprice; ?>,-</sub></span>
                                        
                                    </div>
                                   <?php } ?>
									<?php if ($product->isAvailable()) :?>
                                            <span class="check-list"><?= $block->escapeHtml(__('Uit voorraad leverbaar')) ?></span>
                                        <?php else :?>
                                           <span class="list"><?= $block->escapeHtml(__('Binnen 4 weken in huis')) ?></span>
                                        <?php endif; ?>
									
								</div>
							</div>
						</div>
					<?php }  ?>
						
					</div>
				<?php } ?>
				</div>
			</aside>

			<aside class="main-block view-block">
				<div class="container">
					<div class="inner">
						<div class="row">							
							<?php
							echo $this->getLayout()
							->createBlock('Magento\Cms\Block\Block')
							->setBlockId('home_custom_featured')
							->toHtml();
						?>
						</div>
					</div>
				</div>
			</aside>

			<aside class="main-block services-block">
				<div class="container">
					<ul class="row">
						<?php
							echo $this->getLayout()
							->createBlock('Magento\Cms\Block\Block')
							->setBlockId('home_service_block')
							->toHtml();
						?>
					</ul>
				</div>
			</aside>
		