<!--begin template -->
<section id="template">
	<?php 
		$objectManager11 = \Magento\Framework\App\ObjectManager::getInstance();
    $category11 = $objectManager11->get('Magento\Framework\Registry')->registry('current_category');
    if(is_null($category11))  {
       $class = "";
   } else {
        $subcats = $category11->getChildrenCategories();
        $class =   (count($subcats) > 0) ? "parent-cats" : "";
   }
	?>
	<!-- begin layout -->
	<section id="layout" class="<?php echo $class; ?>">
		
		<!-- begin header -->
		<header id="header-wrap">
			<div class="headertop">
				<i></i> Gratis Thuisbezorgd
			</div>
			<div class="headermiddle">
				<div class="container">
					<div class="row">
						<div class="header-left">
							<div class="mtoggle"><div></div><div></div>MENU</div>
							<div class="logo"><a href="<?php echo $this->getBaseUrl();?>"><?php echo $this->getChildHtml("logo"); ?></a>
							</div>
						</div>
						<div class="header-right">
							<div class="search-panel">
								 <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Search::form.mini.phtml")->toHtml();?>
								 <?php /* ?>
								<input type="text" placeholder="Waar ben je naar op zoek?"/>
								<input type="submit" />
								<?php */ ?>
							</div>
							<div class="rightlinks">
								<ul>
								<li>	
									<a href="#" class="favbtn"></a>
								</li>
								<li>
									<a href="https://dev.misterbed.nl/customer/account" class="profilebtn"></a>
								</li>
								<li>									
									<?php echo $this->getChildHtml("minicart"); ?>
								</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="headerbottom">
				<div class="container">
					<?php 
					echo $this->getChildHtml('catalog.topnav');
					?>
				</div>
			</div>
		</header>
		
		<!-- start content -->
		<section id="content-wrap">		