<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
//echo $category->getId();
//echo $category->getName();

$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$titleHtml = '';
if (trim($block->getPageHeading())) {
    $titleHtml = '<span class="base" data-ui-id="page-title-wrapper" '
        . $block->getAddBaseAttribute()
        . '>'
        . $block->escapeHtml($block->getPageHeading())
        . '</span>';
}
?>
<?php if ($titleHtml) : ?>
<div class="container">    
<div class="page-title-wrapper<?= $block->escapeHtmlAttr($cssClass) ?>">
     <?php if(is_null($category)) { ?>
    
<?php  } else { ?>
        <span class="tagline2"><?php echo $category->getName(); ?></span>
<?php } ?>
    <h1 class="page-title"
        <?php if ($block->getId()) : ?> id="<?= $block->escapeHtmlAttr($block->getId()) ?>" <?php endif; ?>
        <?php if ($block->getAddBaseAttributeAria()) : ?>
            aria-labelledby="<?= $block->escapeHtmlAttr($block->getAddBaseAttributeAria()) ?>"
        <?php endif; ?>>
        <?= /* @noEscape */ $titleHtml ?>
    </h1>
    <?= $block->getChildHtml() ?>
</div>
</div>
<?php endif; ?>
<script>
    require([
        'jquery',
        'js/select/Selectyze.jquery'        
    ], function($){
        $titls = $('.page-title-wrapper.product').html();
        $('.catalog-product-view.page-layout-1column .column.main .column-right').prepend($titls);
    });
</script>