<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if ($_description = $block->getCurrentCategory()->getDescription()) :
        $objectManager11 = \Magento\Framework\App\ObjectManager::getInstance();    
       $category11 = $objectManager11->get('Magento\Framework\Registry')->registry('current_category');
       
        $_category = $objectManager11->create('Magento\Catalog\Model\Category')->load($category11->getId()); 
        $_outputhelper    = $this->helper('Magento\Catalog\Helper\Output');          

?>
<!--     <div class="category-description"> -->
	
	<div class="categories-block product container">
		<div class="intro-panel">		
            <div class="intro-panel-left">
                  <h3><?php echo $category11->getName(); ?></h3>  			
                 <?= /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->categoryAttribute(
                    $block->getCurrentCategory(),
                     $_description,
                     'description'
                ) ?>
            </div>
            <div class="intro-panel-right">
                 <?php 
                    $_imgHtml   = '';
                    if ($_imgUrl = $_category->getImageUrl()) {
                    $_imgHtml = '<img src="' . $_imgUrl . '" />';
                    $_imgHtml = $_outputhelper->categoryAttribute($_category, $_imgHtml, 'image');
                    /* @escapeNotVerified */ echo $_imgHtml;
                    }
                 ?>
            </div> 		
	</div>
<?php endif; ?>
<style type="text/css">
	em.fas.fa-angle-down {
    padding-left: 11px;
}
</style>
